		<div class="about_container">
		
			<div id="biography">
			<?php echo img(array('src' => 'images/candle.gif', 'alt' => 'Animated Candle', 'id' => 'candle')); ?><p>
			<p id="1st_para">
				Nicholas Weisner was born to Brian and Sandra Weisner on 12 September 1986. He had one brother named Justin and they lived in East Hartford, Connecticut from 1986 until 1994 when they moved to Stafford Springs. Nick, as he was affectionaly known by family and friends, was a nice and outgoing kid who had no problems in making friends and was adored by his teachers and other adults who met him. While in East Hartford, Nick played Tee Ball with the town sponsered baseball program that also included regular baseball. As a child, Nick enjoyed Teenage Mutant Ninja Turtles and He-Man.
				<p>
				After moving to Stafford Springs, Nick would start school in the 3rd grade at West Stafford School, continue through the 4th & 5th grades at Earl M. Witt Intermediate School, go on to Stafford Middle School for 6th, 7th, & 8th before finishing at Stafford High School when he graduated from high school in June of 2004. Some of the sports activities that Nick participated in while in Stafford included Tae Kwon Do from 1995 - 1997 where he earned his rank as a blue belt, Stafford Youth Basketball in 1995, and he played high school football during his freshmen year. When Nick was 10, he was introduced to one of his favorite past times when he started listening to Heavy Metal music. Nick would also make friends with kids that would be his life long friends that were still friends up until his death. 
				<p>
				Following high school, Nick would work numerous jobs with minimial results in finding a career. On 10 October 2007, Nick would enlist into the United States Army as a Heavy Equipment Operater. He was sent to Fort Lenoard Wood in Missouri for Basic Training and Advanced Individual Training (AIT) to learn his job. Nick was able to be sent home for Christmas in 2007 to enjoy the holidays with his family. Nick was then stationed at Schofield Barracks in Honolulu, Hawaii from 2008 until his discharge in September 2011. While stationed with the 523rd Engineers, Nick was deployed to Mosul, Iraq in support of Operation Iraqi Freedom in November of 2008 until his redeployment back to Hawaii in November 2009. (Fun fact: his brother Justin, a Sergeant with 10th Mountain Division out of Fort Drum, NY was deployed to Iraq a month before Nick left Iraq, which would mark the only time the brothers would be in Iraq at the same time while in the service.) Nick was promoted 2 times from E1 Private to E4 Specialist in 2 years with his final promotion happening on 01 December 2009. Nick would be deployed to the Phillippees in March 2011 where he helped with some construction over in the area. Nick was honorable discharged from the United States Army on September 14, 2011.
				<p>
				Sadly, Nick would unexpectedly pass away on 14 November 2011 in the townhouse he shared with his brother (also recently discharged out of the Army) in Vernon, Connecticut. At the time of his death, he was working with a couple of his friends doing concrete work with a company out of Stafford Springs. He had just recently enrolled with Branford Hall in Windsor so that he can learn to be an x-ray tech. 
				
				
				
			</div>
		</div>